Avoid overwriting line type in word diff
When "reading_diff_chunk" is set and "combined_diff" isn't, we must have a
line that is one of context/added/deleted, so the check is redundant.

Found by Clang:

	$ CC=clang TIG_BUILD=config.make tools/travis.sh
	src/diff.c:377:27: error: converting the enum constant to a boolean [-Werror,-Wint-in-bool-context]
	                   (type = LINE_DEFAULT ||